const auctions=[
{id:1,title:'Midnight Abstract',cat:'Art',bid:18500,img:'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=80',end:Date.now()+3600000*7},
{id:2,title:'Vintage Chronograph',cat:'Watches',bid:8200,img:'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80',end:Date.now()+3600000*3},
{id:3,title:'Royal Gem Necklace',cat:'Jewelry',bid:12400,img:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80',end:Date.now()+3600000*11},
{id:4,title:'Classic Camera No. 7',cat:'Collectibles',bid:3400,img:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80',end:Date.now()+3600000*5},
{id:5,title:'Golden Landscape',cat:'Art',bid:9600,img:'https://images.unsplash.com/photo-1577083288073-40892c0860a4?auto=format&fit=crop&w=900&q=80',end:Date.now()+3600000*9},
{id:6,title:'Heritage Timepiece',cat:'Watches',bid:11200,img:'https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&w=900&q=80',end:Date.now()+3600000*14}
];
function timeLeft(t){let s=Math.max(0,Math.floor((t-Date.now())/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=s%60;return `${h}h ${m}m ${sec}s`}
function renderAuctions(){let cat=document.querySelector('#categoryFilter').value,sort=document.querySelector('#sortFilter').value;let a=auctions.filter(x=>cat==='all'||x.cat===cat);if(sort==='price')a.sort((x,y)=>y.bid-x.bid);else a.sort((x,y)=>x.end-y.end);document.querySelector('#auctionGrid').innerHTML=a.map(x=>`<article class="card"><img src="${x.img}" alt="${x.title}"><div class="card-body"><span class="tag">${x.cat} · LIVE AUCTION</span><h3>${x.title}</h3><div class="bid"><div><small>Current bid</small><br><b>₹${x.bid.toLocaleString('en-IN')}</b></div><div><small>Ends in</small><br><b class="timer" data-end="${x.end}">${timeLeft(x.end)}</b></div></div><button onclick="openBid(${x.id})">View & Place Bid</button></div></article>`).join('')}
function openBid(id){let x=auctions.find(a=>a.id===id);document.querySelector('#modalContent').innerHTML=`<p class="eyebrow">${x.cat} AUCTION</p><h2>${x.title}</h2><p>Current bid: <b>₹${x.bid.toLocaleString('en-IN')}</b></p><p>Secure bidding is available for registered bidders.</p><form onsubmit="placeBid(event,${id})"><input id="bidAmount" type="number" min="${x.bid+1}" placeholder="Enter bid amount" required><button class="primary">Place Bid</button></form>`;document.querySelector('#modal').style.display='flex'}
function placeBid(e,id){e.preventDefault();let v=+document.querySelector('#bidAmount').value;let x=auctions.find(a=>a.id===id);if(v>x.bid){x.bid=v;closeModal();renderAuctions();alert('Bid placed successfully! (Demo)')}}
function openModal(type){document.querySelector('#modalContent').innerHTML=type==='login'?`<h2>Login</h2><form onsubmit="demoLogin(event)"><input type="email" placeholder="Email" required><input type="password" placeholder="Password" required><button class="primary">Login</button></form><p>New bidder? <a href="#" onclick="openModal('register')">Register here</a></p>`:`<h2>Register to Bid</h2><form onsubmit="demoRegister(event)"><input placeholder="Full name" required><input type="email" placeholder="Email" required><input type="tel" placeholder="Phone" required><input type="password" placeholder="Create password" required><button class="primary">Create Account</button></form>`;document.querySelector('#modal').style.display='flex'}
function closeModal(){document.querySelector('#modal').style.display='none'}
function demoLogin(e){e.preventDefault();closeModal();alert('Login successful! (Demo)')}
function demoRegister(e){e.preventDefault();closeModal();alert('Registration submitted! (Demo verification)')}
function submitContact(e){e.preventDefault();e.target.reset();alert('Inquiry sent successfully! (Demo)')}
renderAuctions();setInterval(()=>document.querySelectorAll('.timer').forEach(t=>t.textContent=timeLeft(+t.dataset.end)),1000);